### ISSUE TITLE
Problem trying to terminate already terminated childWatcher on system startup

### ISSUE THREAD

**Issue by marianopeck** [marianopeck/OSSubprocess#17]
It seems that we were trying to terminate the `childWatcher` in `#finalizePreviousSession` even when the process was already terminated, and so we were getting the `ProcessAlreadyTerminating` exception. Why was the `childWatcher` already terminated? I really don't know. But it seems that making the code more robust for this case does solve the issue:

```Smalltalk
childWatcher ifNotNil: [ 
		childWatcher isTerminated ifFalse: [ childWatcher terminate ].
		childWatcher := nil.
	].
```

Thanks to Norbert Halt for the bug report and for sharing the image with the problem.

**Comment by theseion** [comment]
You should probably usr `#isTerminating` instead of `#isTerminated`. That will also answer true if the process is not terminated yet but `#terminate` has already been sent.
