### ISSUE TITLE
Rename `pwd:` to `workingDirectory:`

### ISSUE THREAD

**Issue by peteruhnak** [marianopeck/OSSubprocess#18]
Can `pwd:` method be changed to `workingDirectory:` or something similar?
- in linux `pwd` is _print working directory_ --- a read only retrieval
- it's not a very descriptive name

**Comment by marianopeck** [comment]
Hi @peteruhnak 

Yes, that makes total sense. We should also update all the documentation. I would do this in the dev branch. Give some time and I will try to do it. 

Thanks!

**Comment by guillep** [comment]
Was this fixed? Maybe it can be closed :)

**Comment by marianopeck** [comment]
Yeah, it was fixed and already in `master`.
