### ISSUE TITLE
[Question]: Why is API So Different from OSProcess?

### ISSUE THREAD

**Issue by seandenigris** [marianopeck/OSSubprocess#24]
I'm just wondering if there was a calculated reason to depart from the existing API. It would seem to make things much easier to unify as much as possible…

**Comment by pdebruic** [comment]
+1

**Comment by marianopeck** [comment]
Because part of the reasons of developing this new tool is because I don't like OSProcess API.

**Comment by pdebruic** [comment]
Makes sense.  How do you feel about including a shim to mock the old API onto the new? 

I could look into writing what I think I need for a start.


Kind of like MockGemStone but for OSProcess things.  Would be good to translate to GemStone's performOnServer: too I guess.

**Comment by marianopeck** [comment]
Hi @pdebruic 

If you want to go ahead with that kind of mock or compatibility package then do it. I am not against. but please make it a separate package. Also, as for GemStone performOnServer: , for my case for example, I have that split into my own (my product) compatibility packages. So I have a polymorphic API that on Pharo it uses OSSubprocess and in GemStone it uses `performOnServer:`. 

Cheers,

**Comment by guillep** [comment]
I also agree that OSSubprocess API is ugly.

Now, regarding this issue, it was open in february and no action was taking since. I vouch to close it for now.

**Comment by marianopeck** [comment]
Guille you mean OSSubprocess is ugly or osprocess? Typo?

**Comment by guillep** [comment]
Typo :) I fixed it.
