### ISSUE TITLE
Add OS signal sending from process

### ISSUE THREAD

**Issue by marianopeck** [marianopeck/OSSubprocess#4]
The idea is that we can have messages like `sigterm`, `sigkill` so that we can send such signals to a particular child process.  We can base the effort in what OSProcess has. See class ExternalUnixOSProcess protocol 'OS signal sending' and class UnixProcess protocol 'OS signal sending'

**Comment by marianopeck** [comment]
Max,  

I added the support for signals and you can see the 2 tests I added:  `testSigTermInsideLoop` and `testSigTerm`. I think such support (`sigterm`) is enough as for what matters to the framework. 

What I originally thought about `killIfTakesLongerThan:` is too much dependent of a particular scenario. Others may want another signal or another condition. So I think the framework should just allow signaling and then it's up to the user to decide what signal and when to send it. 

Agree?

**Comment by theseion** [comment]
I can't find those tests. Where are they?

**Comment by marianopeck** [comment]
Sorry Max, those are in the master, not in the stable release. 
You must execute something like:

```Smalltalk
Metacello new
    baseline: 'OSSubprocess';
    repository: 'github://marianopeck/OSSubprocess:master/repository';
    load.
```

**Comment by marianopeck** [comment]
BTW, I was planning to add methods like `terminate` and `kill` which will internally do `sigterm` and `sigkill`.

**Comment by theseion** [comment]
> What I originally thought about killIfTakesLongerThan: is too much dependent of a particular scenario. Others may want another signal or another condition. So I think the framework should just allow signaling and then it's up to the user to decide what signal and when to send it.

Yes, I agree.

I noticed that `#sigTerm` uses a primitive for exactly that signal. I'm used to the `kill` command and to the way signals are specified there (e.g. by number or name). Naming a signal explicitly makes it more flexible I think, especially since you would only need a single primitive to handle all signals. You should still offer convenience methods for accessing the signals of course (I don't think you really want users specifying signal names as strings :))

**Comment by marianopeck** [comment]
OK, we already have all singals sending (a method per signal) and we also included 2 faclities methods `terminate` and `kill`.
